DEBUG    twister_harness.device.factory:factory.py:37 Get device type "hardware"
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac6406e0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac6108c0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac4547d0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'193'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'projects 0-1/1'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:07 GMT'), (b'x-kong-upstream-latency', b'24'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac456350>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac610dd0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac5f5ba0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'297'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:07 GMT'), (b'x-kong-upstream-latency', b'19'), (b'x-kong-proxy-latency', b'13'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/devices "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac5f6190>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac6110a0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac4505f0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'205'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:08 GMT'), (b'x-kong-upstream-latency', b'44'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/devices/68e0144fb6c731f600fa4680/credentials "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.hardware_adapter:utils.py:37 Flashing command: /root/venv/bin/west flash --skip-rebuild --build-dir /__w/golioth-firmware-sdk/golioth-firmware-sdk/twister-out/rak5010_nrf52840/zephyr/settings/sample.golioth.settings --runner blackmagicprobe -- --gdb=/usr/bin/gdb
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:135 Flashing finished
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
ERROR    twister_harness.device.hardware_adapter:hardware_adapter.py:154 Cannot open connection: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
Traceback (most recent call last):
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/golioth-firmware-sdk/golioth-firmware-sdk/zephyr/scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py", line 145, in _connect_device
    self._serial_connection = serial.Serial(
                              ~~~~~~~~~~~~~^
        serial_name,
        ^^^^^^^^^^^^
    ...<4 lines>...
        timeout=self.base_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/venv/lib/python3.13/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
    ~~~~~~~~~^^
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
ERROR    twister_harness.device.hardware_adapter:hardware_adapter.py:154 Cannot open connection: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
Traceback (most recent call last):
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/golioth-firmware-sdk/golioth-firmware-sdk/zephyr/scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py", line 145, in _connect_device
    self._serial_connection = serial.Serial(
                              ~~~~~~~~~~~~~^
        serial_name,
        ^^^^^^^^^^^^
    ...<4 lines>...
        timeout=self.base_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/venv/lib/python3.13/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
    ~~~~~~~~~^^
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
ERROR    twister_harness.device.hardware_adapter:hardware_adapter.py:154 Cannot open connection: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
Traceback (most recent call last):
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/golioth-firmware-sdk/golioth-firmware-sdk/zephyr/scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py", line 145, in _connect_device
    self._serial_connection = serial.Serial(
                              ~~~~~~~~~~~~~^
        serial_name,
        ^^^^^^^^^^^^
    ...<4 lines>...
        timeout=self.base_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/venv/lib/python3.13/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
    ~~~~~~~~~^^
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
ERROR    twister_harness.device.hardware_adapter:hardware_adapter.py:154 Cannot open connection: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
Traceback (most recent call last):
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/golioth-firmware-sdk/golioth-firmware-sdk/zephyr/scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py", line 145, in _connect_device
    self._serial_connection = serial.Serial(
                              ~~~~~~~~~~~~~^
        serial_name,
        ^^^^^^^^^^^^
    ...<4 lines>...
        timeout=self.base_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/venv/lib/python3.13/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
    ~~~~~~~~~^^
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
ERROR    twister_harness.device.hardware_adapter:hardware_adapter.py:154 Cannot open connection: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
Traceback (most recent call last):
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/golioth-firmware-sdk/golioth-firmware-sdk/zephyr/scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py", line 145, in _connect_device
    self._serial_connection = serial.Serial(
                              ~~~~~~~~~~~~~^
        serial_name,
        ^^^^^^^^^^^^
    ...<4 lines>...
        timeout=self.base_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/venv/lib/python3.13/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
    ~~~~~~~~~^^
  File "/root/venv/lib/python3.13/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00'
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
DEBUG    twister_harness.helpers.utils:utils.py:22 Found matching key: CONFIG_SHELL_PROMPT_UART="uart:~$ "
INFO     twister_harness.fixtures:fixtures.py:78 Wait for prompt
DEBUG    twister_harness.helpers.shell:shell.py:49 Got prompt
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac46e030>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac569130> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac46e140>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:46 GMT'), (b'x-kong-upstream-latency', b'58'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google'), (b'transfer-encoding', b'chunked')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/devices/68e0144fb6c731f600fa4680/settings "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac61a350>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac6129f0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac61a450>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:47 GMT'), (b'x-kong-upstream-latency', b'40'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google'), (b'transfer-encoding', b'chunked')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/settings "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac5d73e0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac612b10> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac5d74d0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'PUT']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'PUT']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'PUT']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'217'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:47 GMT'), (b'x-kong-upstream-latency', b'24'), (b'x-kong-proxy-latency', b'3'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: PUT https://api.golioth.io/v1/projects/firmware_ci/settings/663a50a9841eb6679ef3692a "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'PUT']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac63add0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac612f90> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac63acf0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'207'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'credentials 0-1/1'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:22:50 GMT'), (b'x-kong-upstream-latency', b'19'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/devices/68e0144fb6c731f600fa4680/credentials "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [msettings set golioth/psk-id generated-wumriscqSuGRyHXl@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk-id to generated-wumriscqSuGRyHXl@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk-id saved as generated-wumriscqSuGRyHXl@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [msettings set golioth/psk generated-wumriscqSuGRyHXl
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk to generated-wumriscqSuGRyHXl
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk saved as generated-wumriscqSuGRyHXl
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [mwifi cred add -k 1 -s "***MIKES_ORANGE_PI_WIFI_SSID***" -p "***MIKES_ORANGE_PI_WIFI_PSK***"
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;31mwifi: command not found
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [m[1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [mwifi cred auto_connect
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;31mwifi: command not found
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [m[1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:00.418,304] [0m<inf> fs_nvs: alloc wra: 0, fa8[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:00.418,334] [0m<inf> fs_nvs: data wra: 0, ac[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:00.418,365] [0m<inf> golioth_settings_autoload: Loading settings[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:00.418,792] [0m<dbg> device_settings: main: Start Golioth Device Settings sample[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:00.418,792] [0m<inf> golioth_samples: Bringing up network interface[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:00.418,914] [0m<inf> golioth_samples: Waiting to obtain IP address[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:21.911,865] [1;33m<wrn> modem_chat: quectel_bg95_init_chat_script: timed out[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:36.804,138] [0m<inf> golioth_mbox: Mbox created, bufsize: 1320, num_items: 10, item_size: 120[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:38.206,604] [0m<inf> golioth_coap_client_zephyr: Golioth CoAP client connected[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.206,817] [0m<inf> device_settings: Sending hello! 0[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.206,909] [0m<inf> device_settings: Golioth client connected[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.206,909] [0m<inf> golioth_coap_client_zephyr: Entering CoAP I/O loop[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.657,531] [0m<inf> device_settings: Setting loop delay to 1 s[0m
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac621cc0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac613650> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac731b50>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:23:24 GMT'), (b'x-kong-upstream-latency', b'16'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google'), (b'transfer-encoding', b'chunked')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/devices/68e0144fb6c731f600fa4680/settings "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac731fd0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac613a40> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac5bdb20>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:23:24 GMT'), (b'x-kong-upstream-latency', b'8'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google'), (b'transfer-encoding', b'chunked')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/settings "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac5bdc80>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac613c80> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac635770>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'256'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:23:25 GMT'), (b'x-kong-upstream-latency', b'29'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/settings "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.657,653] [1;31m<err> golioth_settings: Failed to send a response to server: -12[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.695,739] [0m<inf> device_settings: Setting loop delay to 1 s[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:38.696,136] [1;31m<err> golioth_settings: Failed to send a response to server: -12[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:40.695,953] [0m<inf> device_settings: Setting loop delay to 5 s[0m
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:190 Closed serial connection for /dev/serial/by-id/usb-ZEPHYR_RAK5010_Zephyr_A79B173FF273CE6E-if00
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac636850>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffffac612720> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffffac569130>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'2'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Fri, 03 Oct 2025 18:23:26 GMT'), (b'x-kong-upstream-latency', b'21'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: DELETE https://api.golioth.io/v1/projects/firmware_ci/devices/68e0144fb6c731f600fa4680 "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete